server:
    port: 8090

spring:
  application:
    name: mineCenter
  datasource:
    druid:
      name: devplat
      url: jdbc:mysql://yourIp/yourDataBase?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: yourUserName
      password: yourPassWord
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    host: yourIp
    port: yourPort
    password: yourPasswd

mybatis:
  mapper-locations: classpath:src/main/resources/mapping/*.xml
  type-aliases-package: com.mineserver.home.page.model


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mapper:
    not-empty: true

logging:
  level:
    root: info
    com.minecenter: debug
    com.minecenter.mapper: debug
    org.apache.shiro: error
  file: log/minecenter.log
